#spring 기본설정
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # url: jdbc:sqlserver://devdb.cesco.biz:11433;DatabaseName=CESCO_ACCOUNT;
    url: jdbc:sqlserver://maindb.cesco.biz:11433;DatabaseName=CESCO_ACCOUNT;
    username: cescoapi
    password: Ce$c0Ap!19
    # username: 21297
    # password: Rlawodlr!00
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 30000
      poolName: maindb-pool
      maxLifetime: 2000000
      connectionTimeout: 30000
    
---

#mybatis 설정
mybatis:
  mapper-locations: classpath*:mappers/*/*.xml

---

#logging 설정
logging:
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 7
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(-){faint} %clr([%10.10t]){faint} %clr(%-30.30logger{29}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(-){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: warn
    '[com.cesco.api.cesnetapi]': info
    '[com.cesco.api.cesnetapi.config]': debug